ALTER TABLE ValoresTextosPaginados
DROP COLUMN IF EXISTS Habilitado,
DROP COLUMN IF EXISTS VigenteDe,
DROP COLUMN IF EXISTS VigenteAte;

ALTER TABLE ValoresJsonPaginados
DROP COLUMN IF EXISTS Habilitado,
DROP COLUMN IF EXISTS VigenteDe,
DROP COLUMN IF EXISTS VigenteAte;

ALTER TABLE ValoresBinariosBase64Paginados
DROP COLUMN IF EXISTS Habilitado,
DROP COLUMN IF EXISTS VigenteDe,
DROP COLUMN IF EXISTS VigenteAte;
